In [72]:
import numpy as np
import torch

In [52]:
dets=np.random.randn(5,5)

In [53]:
x1 = dets[:, 0]
y1 = dets[:, 1]
x2 = dets[:, 2]
y2 = dets[:, 3]
scores = dets[:, 4]

In [60]:
order = scores.argsort()[::-1]
order

array([3, 4, 1, 0, 2])

In [59]:
i=order.item(0)
i

3

In [62]:
xx1 = np.maximum(x1[i], x1[order[1:]])
xx1

array([ 0.31695022, -0.06774948,  0.017093  ,  0.35174896])

In [57]:
order[1:]

array([4, 1, 0, 2])

In [61]:
x1[i]

-0.5514087139840629

In [63]:
yy1 = np.maximum(y1[i], y1[order[1:]])
xx2 = np.minimum(x2[i], x2[order[1:]])
yy2 = np.minimum(y2[i], y2[order[1:]])

w = np.maximum(0.0, xx2 - xx1 + 1)
h = np.maximum(0.0, yy2 - yy1 + 1)
inter = w * h

In [64]:
w

array([0.        , 0.13835346, 0.        , 0.        ])

In [66]:
h

array([0.14244231, 0.        , 0.        , 0.30354364])

In [65]:
inter

array([0., 0., 0., 0.])

In [71]:
dets.size

25

In [73]:
x=torch.randn(5,5)

In [78]:
x.new(3,3).zero_()

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [79]:
getattr(x)

TypeError: getattr expected at least 2 arguments, got 1

In [84]:
callable(torch.randn)

True

In [85]:
callable(1)

False

In [86]:
locals

<function locals()>

In [87]:
__all__

NameError: name '__all__' is not defined

In [95]:

def foo(arg, a):
	x = 1
	y = 'xxxxxx'
	for i in range(10):
		j = 1
		k = i
	print (locals[i])


In [96]:
foo(1,2)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [98]:
tem=np.arange(-1, 1, 2.0/(32))

In [115]:
2.0/(32)

0.0625

In [118]:
tem.shape

(32,)

In [121]:
tem_1=np.expand_dims(tem, 0)

In [128]:
tem_1.shape

(1, 32)

In [122]:
tem

array([-1.    , -0.9375, -0.875 , -0.8125, -0.75  , -0.6875, -0.625 ,
       -0.5625, -0.5   , -0.4375, -0.375 , -0.3125, -0.25  , -0.1875,
       -0.125 , -0.0625,  0.    ,  0.0625,  0.125 ,  0.1875,  0.25  ,
        0.3125,  0.375 ,  0.4375,  0.5   ,  0.5625,  0.625 ,  0.6875,
        0.75  ,  0.8125,  0.875 ,  0.9375])

In [123]:
tem_1

array([[-1.    , -0.9375, -0.875 , -0.8125, -0.75  , -0.6875, -0.625 ,
        -0.5625, -0.5   , -0.4375, -0.375 , -0.3125, -0.25  , -0.1875,
        -0.125 , -0.0625,  0.    ,  0.0625,  0.125 ,  0.1875,  0.25  ,
         0.3125,  0.375 ,  0.4375,  0.5   ,  0.5625,  0.625 ,  0.6875,
         0.75  ,  0.8125,  0.875 ,  0.9375]])

In [126]:
tem_2=np.expand_dims(np.repeat(tem_1, repeats = 32, axis = 0).T, 0)

In [138]:
tem_22=np.repeat(tem_1, repeats = 32, axis = 0)
tem_22

array([[-1.    , -0.9375, -0.875 , ...,  0.8125,  0.875 ,  0.9375],
       [-1.    , -0.9375, -0.875 , ...,  0.8125,  0.875 ,  0.9375],
       [-1.    , -0.9375, -0.875 , ...,  0.8125,  0.875 ,  0.9375],
       ...,
       [-1.    , -0.9375, -0.875 , ...,  0.8125,  0.875 ,  0.9375],
       [-1.    , -0.9375, -0.875 , ...,  0.8125,  0.875 ,  0.9375],
       [-1.    , -0.9375, -0.875 , ...,  0.8125,  0.875 ,  0.9375]])

In [136]:
tem_22.shape

(1024, 1)

In [127]:
tem_2.shape

(1, 32, 32)

In [140]:
grid = np.zeros( [32, 32, 3], dtype=np.float32)

In [141]:
grid[:,:,1]=tem_2

In [143]:
grid[:,:,1].shape

(32, 32)

In [142]:
grid.shape

(32, 32, 3)

In [152]:
grid=torch.from_numpy(grid)

In [168]:
inputs=torch.randn(1,32,32,3)

In [187]:
batchgrid=inputs.new(torch.Size([inputs.size(0)]) + grid.size()).zero_().shape

In [188]:
torch.Size([inputs.size(0)])

torch.Size([1])

In [189]:
[inputs.size(0)]

[1]

In [190]:
torch.Size([inputs.size(0)])+ grid.size()

torch.Size([1, 32, 32, 3])

In [191]:
batchgrid[0] = grid.astype(batchgrid[0])

AttributeError: 'Tensor' object has no attribute 'astype'

In [194]:
tem=np.random.randn(32,32,3)

In [195]:
batchgrid[0] = tem.astype(batchgrid[0])

TypeError: data type not understood

In [197]:
tem.astype(float)

array([[[-1.02675174, -0.8233831 ,  0.7103046 ],
        [ 0.2711673 , -0.11647799, -0.87285126],
        [ 0.92256682,  0.70876347,  1.81557876],
        ...,
        [ 0.37515934,  0.49836147, -0.24927989],
        [-1.95658174, -1.17048171,  0.16915116],
        [ 0.17835087, -0.28310996,  0.59141573]],

       [[-0.02923663, -0.43294314, -0.96295621],
        [-1.36272879, -1.53158416, -0.07079563],
        [ 0.96847216,  0.76879555,  2.06164534],
        ...,
        [-0.97185641, -0.67998536, -1.42667279],
        [ 2.56402754, -1.38133813,  1.11151656],
        [ 0.12135514, -1.84137037, -0.18560238]],

       [[-1.21706983, -0.8492042 ,  0.35881243],
        [ 1.04200458,  0.05830195,  0.19438207],
        [-0.63160346,  0.55283728,  0.83591305],
        ...,
        [-1.26283748,  1.02443609,  2.20803421],
        [ 1.30062906, -0.85213893,  1.1190759 ],
        [-0.80594708, -0.8517061 ,  2.14390394]],

       ...,

       [[ 1.35360762,  0.29883402,  1.00586919],
        [ 0

In [222]:
x,y=np.meshgrid(x,x)

In [232]:
x=np.arange(1,5)

In [233]:
x=torch.from_numpy(x)

In [225]:
x.ravel()

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [226]:
y.ravel()

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [234]:
x

tensor([1, 2, 3, 4])

In [235]:
x.contiguous()

tensor([1, 2, 3, 4])

In [248]:
torch.cat(tuple(tem), 1).shape

torch.Size([3, 320, 32])

In [243]:
tem=torch.randn(10,3,32,32)

In [256]:
round(12.5555)

13

In [251]:
help("round")

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [257]:
rois = torch.rand((10, 5))

In [258]:
rois

tensor([[0.5279, 0.7551, 0.3184, 0.1435, 0.3946],
        [0.2948, 0.1556, 0.3503, 0.4462, 0.2440],
        [0.1273, 0.7052, 0.4834, 0.2403, 0.8499],
        [0.7889, 0.6506, 0.4308, 0.5820, 0.6766],
        [0.8508, 0.9136, 0.0067, 0.7351, 0.1894],
        [0.2553, 0.9138, 0.1888, 0.7547, 0.3941],
        [0.2022, 0.2996, 0.1295, 0.9582, 0.2699],
        [0.8190, 0.8283, 0.9139, 0.9794, 0.8533],
        [0.5312, 0.3211, 0.8061, 0.0591, 0.3841],
        [0.2085, 0.0087, 0.3798, 0.0114, 0.8659]])

In [259]:
rois[:, 0] = rois[:, 0] * 8

In [261]:
rois/8

tensor([[5.2794e-01, 9.4390e-02, 3.9796e-02, 1.7940e-02, 4.9322e-02],
        [2.9482e-01, 1.9447e-02, 4.3789e-02, 5.5776e-02, 3.0494e-02],
        [1.2725e-01, 8.8149e-02, 6.0422e-02, 3.0032e-02, 1.0624e-01],
        [7.8888e-01, 8.1325e-02, 5.3850e-02, 7.2748e-02, 8.4573e-02],
        [8.5083e-01, 1.1420e-01, 8.3829e-04, 9.1882e-02, 2.3679e-02],
        [2.5528e-01, 1.1422e-01, 2.3606e-02, 9.4336e-02, 4.9258e-02],
        [2.0221e-01, 3.7454e-02, 1.6182e-02, 1.1978e-01, 3.3736e-02],
        [8.1898e-01, 1.0354e-01, 1.1423e-01, 1.2242e-01, 1.0666e-01],
        [5.3120e-01, 4.0142e-02, 1.0076e-01, 7.3899e-03, 4.8014e-02],
        [2.0849e-01, 1.0914e-03, 4.7479e-02, 1.4191e-03, 1.0824e-01]])

In [262]:
size=(7, 7)

In [263]:
size[0]

7